# http://www.appveyor.com/docs/appveyor-yml
branches:
  only:
    - master
    - develop
    - /\d*\.\d*\.\d*/

image: Visual Studio 2019
test: off

install:
  - ps: Invoke-WebRequest 'https://dot.net/v1/dotnet-install.ps1' -OutFile 'dotnet-install.ps1'
  - ps: ./dotnet-install.ps1 -Version 5.0.100 -InstallDir "C:\Program Files\dotnet"

build_script:
  - cmd: dotnet --info
  - cmd: .\build.cmd CI -Verbose

artifacts:
  - path: \artifacts\*.*
  - path: output/test-results/*.trx
  - path: output/test-results/*.xml

nuget:
  disable_publish_on_pr: true

skip_commits:
  files:
    - '**/*.md'