# http://www.appveyor.com/docs/appveyor-yml
branches:
  only:
    - master
    - develop
    - /\d*\.\d*\.\d*/

image: Visual Studio 2019
test: off

environment:
  SignPathAuthToken:
    secure: 2zYYVqBWRInF5x5iO/jpFsIzQAx9AEt6Fas2LBnxMg2fbwPgeWH5CnF9Xy2LmlWVji+WP4eby2/k63dcz8JZ3g==

install:
  - ps: Invoke-WebRequest 'https://dot.net/v1/dotnet-install.ps1' -OutFile 'dotnet-install.ps1'
  - ps: ./dotnet-install.ps1 -Version 5.0.100 -InstallDir "C:\Program Files\dotnet"

build_script:
  - cmd: dotnet --info
  - cmd: .\build.cmd CI -Verbose

after_build:
  - ps: gci -Filter *.trx -Path .\output\test-results\ | % { (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $_.FullName)) }

nuget:
  disable_publish_on_pr: true

skip_commits:
  files:
    - '**/*.md'
